### ISSUE TITLE
"undefined"

### ISSUE THREAD

**Issue by meteormorning** [MarkM-dev/Previews-#3]
Hi for some reason my extension has been stuck with everything saying "undefined" for like a week now. And the extension itself doesnt work anymore, doesnt show my favorites or anything...
![image_2023-06-05_143958756](https://github.com/MarkM-dev/Previews/assets/135654459/4f34d40d-b34e-4ce8-b754-0e6f89092a0f)

**Comment by MarkM-dev** [comment]
The Opera webstore seems to be afk and they haven't tested a new version for a few months, this leaves Opera users behind on updates and more prone to issues.

We strongly recommend Opera browser users to reinstall the extension from the Chrome webstore:
https://chrome.google.com/webstore/detail/previews-for-ttv-yt/hpmbiinljekjjcjgijnlbmgcmoonclah
