### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by samuelitofuerte** [MarkM-dev/Previews-#4]
in all my extension, every word its "undefined" and the extension doesnt work.

**Comment by MarkM-dev** [comment]
The Opera webstore seems to be afk and they haven't tested a new version for a few months, this leaves Opera users behind on updates and more prone to issues.

We strongly recommend Opera browser users to reinstall the extension from the Chrome webstore:
https://chrome.google.com/webstore/detail/previews-for-ttv-yt/hpmbiinljekjjcjgijnlbmgcmoonclah
